Internal Server Error: /authentication/register/
"POST /authentication/register/ HTTP/1.1" 500 98
Internal Server Error: /authentication/login/
"POST /authentication/login/ HTTP/1.1" 500 91
Internal Server Error: /authentication/login/
"POST /authentication/login/ HTTP/1.1" 500 91
Internal Server Error: /shortener/shorten-url/
Traceback (most recent call last):
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: shortener_shortenedurl.short_code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\shortener\views.py", line 17, in shorten_url
    while (ShortenedUrl.objects.filter(short_code=short_code).exists()):
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\models\query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\models\sql\query.py", line 660, in has_results
    return compiler.has_results()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: shortener_shortenedurl.short_code
"POST /shortener/shorten-url/ HTTP/1.1" 500 167207
Internal Server Error: /shortener/shorten-url/
Traceback (most recent call last):
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: shortener_shortenedurl

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\shortener\views.py", line 17, in shorten_url
    while (ShortenedUrl.objects.filter(short_code=short_code).exists()):
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\models\query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\models\sql\query.py", line 660, in has_results
    return compiler.has_results()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: shortener_shortenedurl
"POST /shortener/shorten-url/ HTTP/1.1" 500 167075
Internal Server Error: /shortener/shorten-url/
Traceback (most recent call last):
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: shortener_shortenedurl

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\shortener\views.py", line 17, in shorten_url
    while (ShortenedUrl.objects.filter(short_code=short_code).exists()):
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\models\query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\models\sql\query.py", line 660, in has_results
    return compiler.has_results()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: shortener_shortenedurl
"POST /shortener/shorten-url/ HTTP/1.1" 500 167075
Internal Server Error: /shortener/shorten-url/
Traceback (most recent call last):
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\shortener\views.py", line 23, in shorten_url
    if serializer.is_valid():
       ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 497, in to_internal_value
    for field in fields:
                 ^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 380, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 1105, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 1251, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 1369, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `created_at` is not valid for model `ShortenedUrl` in `shortener.serializers.ShortenedUrlSerializer`.
"POST /shortener/shorten-url/ HTTP/1.1" 500 149647
Internal Server Error: /fXuff2/
Traceback (most recent call last):
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 316, in perform_content_negotiation
    return conneg.select_renderer(request, renderers, self.format_kwarg)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\negotiation.py", line 78, in select_renderer
    raise exceptions.NotAcceptable(available_renderers=renderers)
rest_framework.exceptions.NotAcceptable: Could not satisfy the request Accept header.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 517, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 437, in finalize_response
    neg = self.perform_content_negotiation(request, force=True)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 319, in perform_content_negotiation
    return (renderers[0], renderers[0].media_type)
            ~~~~~~~~~^^^
IndexError: list index out of range
"GET /fXuff2/ HTTP/1.1" 500 99937
Internal Server Error: /fXuff2/
Traceback (most recent call last):
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 316, in perform_content_negotiation
    return conneg.select_renderer(request, renderers, self.format_kwarg)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\negotiation.py", line 78, in select_renderer
    raise exceptions.NotAcceptable(available_renderers=renderers)
rest_framework.exceptions.NotAcceptable: Could not satisfy the request Accept header.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 517, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 437, in finalize_response
    neg = self.perform_content_negotiation(request, force=True)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\views.py", line 319, in perform_content_negotiation
    return (renderers[0], renderers[0].media_type)
            ~~~~~~~~~^^^
IndexError: list index out of range
"GET /fXuff2/ HTTP/1.1" 500 100094
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bc9123\Documents\github\django-link-shortener\backend\venv\Lib\site-packages\rest_framework\response.py", line 59, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
           ^^^^^^^^
AssertionError: .accepted_renderer not set on Response
"GET /favicon.ico HTTP/1.1" 500 74733
